on:
  push:
    branches:
      - master

permissions:
  contents: write
  issues: write
  pull-requests: write

name: Release Flow

jobs:
  release-please:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        elixir: ["1.19.1"]
        otp: ["28.1.1"]
    steps:
      - uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: 336328
          private-key: ${{ secrets.APP_KEY }}

      - name: "Prepare Release"
        id: release
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ steps.app-token.outputs.token }}
          release-type: elixir

      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        if: ${{ steps.release.outputs.release_created }}
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}

      - name: Checkout
        uses: actions/checkout@v4
        if: ${{ steps.release.outputs.release_created }}

      - name: Fetch and Compile Dependencies
        if: ${{ steps.release.outputs.release_created }}
        run: |
          mix deps.get
          mix deps.compile

      - name: Publish to hex.pm
        if: ${{ steps.release.outputs.release_created }}
        run: HEX_API_KEY=${{ secrets.HEX_API_KEY }} mix hex.publish --yes
